In [181]:
source = '''7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1

22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7'''

In [105]:
f=open('input.txt','r')
lines= f.read().split('\n')[:-1]

In [190]:
lines = source.split('\n')

f=open('input.txt','r')
lines= f.read().split('\n')[:-1]

nums = list(map(int,lines[0].split(',')))
#nums
bcount = 0 
import numpy as np
scoreboards = dict()
totalboards = (len(lines)-2)//6 +1
nboard = np.zeros(shape=(totalboards,5,5))
yline=0
for l in  lines[2:]:
    if l =='':
        bcount+=1
        yline=0
    else:
        for xpos,x in enumerate(l.strip().replace('  ',' ').split(' ')):
            #print(xpos,x,yline,bcount)
            nboard[bcount][yline][xpos] = int(x)
        yline+=1
    

In [191]:
nboard

array([[[78., 13.,  8., 62., 67.],
        [42., 89., 97., 16., 65.],
        [ 5., 12., 73., 50., 56.],
        [45., 10., 63., 41., 64.],
        [49.,  1., 95., 71., 17.]],

       [[60., 25., 66., 82., 22.],
        [94., 45., 68.,  5., 12.],
        [46., 44., 48., 31., 34.],
        [10., 56., 37., 96., 81.],
        [99., 39., 84., 32.,  6.]],

       [[11., 86., 77., 36.,  2.],
        [57., 68., 27., 74.,  4.],
        [81., 92., 49., 37., 51.],
        [78., 43., 94., 46., 63.],
        [13., 52., 72., 17., 44.]],

       ...,

       [[ 1., 54., 88., 45., 90.],
        [81., 78., 19.,  8., 40.],
        [17., 74., 69., 87., 33.],
        [ 9., 64., 85., 50., 71.],
        [92., 38., 65., 82., 41.]],

       [[ 2., 62., 96., 60., 81.],
        [51.,  1., 34., 48., 25.],
        [78., 13., 74., 65., 42.],
        [46., 64., 57., 19., 72.],
        [85., 88., 53., 68., 76.]],

       [[57., 95., 40., 92., 27.],
        [65., 37., 42., 90.,  9.],
        [17., 72., 78., 43., 45.

In [192]:
overall = np.zeros(shape=(totalboards,5,5))
len(overall)

100

In [193]:
winner = None
overall = np.zeros(shape=(totalboards,5,5))


for n in nums:
    overall+=nboard==n
    for b in range(totalboards):
        if (5 in overall[b].sum(axis=0)) or (5 in overall[b].sum(axis=1)):
            print(b)
            winner = b
    if winner != None:
        break
int(nboard[winner][overall[winner]==0].sum()*n)

lastwinner = winner


94


In [194]:
winners = []
overall = np.zeros(shape=(totalboards,5,5))

for nindex,n in enumerate(nums): 
    for b in len(overall):
        overall+=nboard==n
        
        if (5 in overall[b].sum(axis=0)) or (5 in overall[b].sum(axis=1)):
            winners.append((nindex,n,b))


TypeError: 'int' object is not iterable

In [195]:
winner = None
overall = np.zeros(shape=(totalboards,5,5))
wonat= dict()
b=0

for npos,n in enumerate(nums):
    #print(n)
    overall+=nboard==n
    for b in range(totalboards):
        if (5 in overall[b].sum(axis=0)) or (5 in overall[b].sum(axis=1)):
            #print(b)
            if b not in wonat.keys():
                wonat[b]=npos


In [196]:
overall[1]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [197]:
biggest = 0
for k,v in  wonat.items():
    #print(k,nums[v])
    if v> biggest:
        lastpos = v
        lastwiningnum = nums[v]
        lastboard = k
        
lastboard,lastwiningnum,lastpos

(93, 20, 84)

In [198]:
winner = None
overall = np.zeros(shape=(totalboards,5,5))


for n in nums[0:lastpos+1]:
    
    overall+=nboard==n
    for b in range(totalboards):
        if (5 in overall[b].sum(axis=0)) or (5 in overall[b].sum(axis=1)):
            #print(b)
            winner = b
int(nboard[lastboard][overall[lastboard]==0].sum()*n)


9020

winner = None
overall = np.zeros(shape=(totalboards,5,5))
wonat= dict()
b=0

for npos,n in enumerate(nums):
    #print(n)
    overall+=nboard==n
    for b in range(totalboards):
        if (5 in overall[b].sum(axis=0)) or (5 in overall[b].sum(axis=1)):
            #print(b)
            if b not in wonat.keys():
                wonat[b]=npos



In [117]:
wonat[-1]

99

In [116]:
overall[wonat[-2]]

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [78]:
overall

array([[[0., 0., 0., 1., 0.],
        [0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 1.],
        [0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 1.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 1.],
        [0., 0., 0., 0., 1.]]])